### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by TheNotary** [tymeart/translations#1]
Hey it was good to see you the other night, thanks for joining my workshop!  Would you be down to pair on a rails app with me sometime before I leave town?

**Comment by tymeart** [comment]
Hey! I'm definitely down to pair on a Rails app! When are you leaving?

**Comment by TheNotary** [comment]
this is my last month, might leave abruptly after someone takes on my apt lease.  I'm at NB today, will probably be around until late if 2day works.

**Comment by tymeart** [comment]
That works. I'll probably be there around 6:30pm.
